/* Copyright (c) 2017, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_SERGEJ_WQHD_DUALDSI_CMD_H_
#define _PANEL_SERGEJ_WQHD_DUALDSI_CMD_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config sergej_wqhd_dualdsi_cmd_panel_data = {
	"qcom,mdss_dsi_sergej_wqhd_dualdsi_cmd", "dsi:0:", "qcom,mdss-dsi-panel",
	9, 1, "DISPLAY_1", 0, 0, 60, 2, 0, 0, 1, 0, 0, 0, 829875000, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution sergej_wqhd_dualdsi_cmd_panel_res = {
	1440, 2560, 76, 32, 16, 0, 4, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info sergej_wqhd_dualdsi_cmd_color = {
	24, 2, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/
static char sergej_wqhd_dualdsi_cmd_on_cmd0[] = {
	0x11, 0x00, 0x05, 0x80
};

static char sergej_wqhd_dualdsi_cmd_on_cmd1[] = {
	0x03, 0x00, 0x39, 0xC0,
	0xF0, 0x5A, 0x5A, 0xFF,
};

static char sergej_wqhd_dualdsi_cmd_on_cmd2[] = {
	0xF2, 0x63, 0x15, 0x80
};

static char sergej_wqhd_dualdsi_cmd_on_cmd3[] = {
	0x07, 0x00, 0x39, 0xC0,
	0xBD, 0x11, 0x01, 0x02,
	0x16, 0x02, 0x16, 0xFF,
};

static char sergej_wqhd_dualdsi_cmd_on_cmd4[] = {
	0x03, 0x00, 0x39, 0xC0,
	0xF0, 0xA5, 0xA5, 0xFF,
};

static char sergej_wqhd_dualdsi_cmd_on_cmd5[] = {
	0x53, 0x20, 0x15, 0x80
};

static char sergej_wqhd_dualdsi_cmd_on_cmd6[] = {
	0x51, 0x80, 0x15, 0x80
};

static char sergej_wqhd_dualdsi_cmd_on_cmd7[] = {
	0x35, 0x00, 0x15, 0x80
};

static char sergej_wqhd_dualdsi_cmd_on_cmd8[] = {
	0x29, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd sergej_wqhd_dualdsi_cmd_on_command[] = {
	{0x4, sergej_wqhd_dualdsi_cmd_on_cmd0, 0x05},
	{0x8, sergej_wqhd_dualdsi_cmd_on_cmd1, 0x00},
	{0x4, sergej_wqhd_dualdsi_cmd_on_cmd2, 0x00},
	{0xc, sergej_wqhd_dualdsi_cmd_on_cmd3, 0x00},
	{0x8, sergej_wqhd_dualdsi_cmd_on_cmd4, 0x17},
	{0x4, sergej_wqhd_dualdsi_cmd_on_cmd5, 0x00},
	{0x4, sergej_wqhd_dualdsi_cmd_on_cmd6, 0x00},
	{0x4, sergej_wqhd_dualdsi_cmd_on_cmd7, 0x00},
	{0x4, sergej_wqhd_dualdsi_cmd_on_cmd8, 0x00}
};

#define SERGEJ_WQHD_DUALDSI_CMD_ON_COMMAND 9


static char sergej_wqhd_dualdsi_cmdoff_cmd0[] = {
	0x28, 0x00, 0x05, 0x80
};

static char sergej_wqhd_dualdsi_cmdoff_cmd1[] = {
	0xff, 0x78, 0x00, 0x80
};

static struct mipi_dsi_cmd sergej_wqhd_dualdsi_cmd_off_command[] = {
	{0x4, sergej_wqhd_dualdsi_cmdoff_cmd0, 0x21},
	{0x4, sergej_wqhd_dualdsi_cmdoff_cmd1, 0x78}
};

#define SERGEJ_WQHD_DUALDSI_CMD_OFF_COMMAND 2


static struct command_state sergej_wqhd_dualdsi_cmd_state = {
	0, 0
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info sergej_wqhd_dualdsi_cmd_command_panel = {
	0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info sergej_wqhd_dualdsi_cmd_video_panel = {
	1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration sergej_wqhd_dualdsi_cmd_lane_config = {
	4, 0, 1, 1, 1, 1
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t sergej_wqhd_dualdsi_cmd_timings[] = {
	0xA1, 0x5A, 0x3E, 0x1, 0x9A, 0x9C, 0x46, 0x5E, 0x3A, 0x3, 0x4
};

static struct panel_timing sergej_wqhd_dualdsi_cmd_timing_info = {
	0, 4, 0x57, 0x4
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence sergej_wqhd_dualdsi_cmd_reset_seq = {
	{1, 20, 20, }, {0, 0, 1, }, 20
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight sergej_wqhd_dualdsi_cmd_backlight = {
	1, 0, 0, 0, 2, "PMIC_8941"
};
static struct labibb_desc sergej_wqhd_dualdsi_cmd_labibb = {
	1, //amoled_panel
	0, //force_config
	4000000, //ibb_min_volt
	4000000, //ibb_max_volt
	4600000, //lab_min_volt
	4600000, //lab_max_volt
	3, //pwr_up_delay
	3, //pwr_down_delay
	1  //ibb_discharge_en
};
#endif /*_PANEL_SERGEJ_WQHD_DUALDSI_CMD_H_*/
