/* Copyright (c) 2017, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_DANICA_1080P_VIDEO_H_
#define _PANEL_DANICA_1080P_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config danica_1080p_video_panel_data = {
	"qcom,mdss_dsi_danica_1080p_video", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution danica_1080p_video_panel_res = {
	1080, 1920, 16, 16, 16, 0, 4, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info danica_1080p_video_color = {
	24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/
static char danica_1080p_video_on_cmd0[] = {
	0x0A, 0xFF, 0xFF, 0x80
};

static char danica_1080p_video_on_cmd1[] = {
	0xFF, 0x23, 0x15, 0x80
};

static char danica_1080p_video_on_cmd2[] = {
	0x20, 0xFF, 0xFF, 0x80
};

static char danica_1080p_video_on_cmd3[] = {
	0x07, 0x20, 0x15, 0x80
};

static char danica_1080p_video_on_cmd4[] = {
	0x46, 0xFF, 0x15, 0x80
};

static char danica_1080p_video_on_cmd5[] = {
	0x08, 0x02, 0x15, 0x80
};

static char danica_1080p_video_on_cmd6[] = {
	0x35, 0x81, 0x15, 0x80
};

static char danica_1080p_video_on_cmd7[] = {
	0x3D, 0x00, 0x15, 0x80
};

static char danica_1080p_video_on_cmd8[] = {
	0xFB, 0x01, 0x15, 0x80
};

static char danica_1080p_video_on_cmd9[] = {
	0x20, 0xFF, 0xFF, 0x80
};

static char danica_1080p_video_on_cmd10[] = {
	0xFB, 0x01, 0x15, 0x80
};

static char danica_1080p_video_on_cmd11[] = {
	0xFF, 0x10, 0x15, 0x80
};

static char danica_1080p_video_on_cmd12[] = {
	0xBB, 0x10, 0x15, 0x80
};

static char danica_1080p_video_on_cmd13[] = {
	0x55, 0x03, 0x15, 0x80
};

static char danica_1080p_video_on_cmd14[] = {
	0x53, 0x2C, 0x15, 0x80
};

static char danica_1080p_video_on_cmd15[] = {
	0x5E, 0x00, 0x15, 0x80
};

static char danica_1080p_video_on_cmd16[] = {
	0x51, 0x80, 0x15, 0x80
};

static char danica_1080p_video_on_cmd17[] = {
	0x36, 0x08, 0x15, 0x80
};

static char danica_1080p_video_on_cmd18[] = {
	0x11, 0x00, 0x05, 0x80
};

static char danica_1080p_video_on_cmd19[] = {
	0x78, 0xFF, 0xFF, 0x80
};

static char danica_1080p_video_on_cmd20[] = {
	0x00, 0x00, 0x00, 0xFF, 0xFE, 0x80
};

static char danica_1080p_video_on_cmd21[] = {
	0x78, 0xFF, 0xFF, 0x80
};

static char danica_1080p_video_on_cmd22[] = {
	0x29, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd danica_1080p_video_on_command[] = {
	{0x4, danica_1080p_video_on_cmd0, 0x00},
	{0x4, danica_1080p_video_on_cmd1, 0x00},
	{0x4, danica_1080p_video_on_cmd2, 0x00},
	{0x4, danica_1080p_video_on_cmd3, 0x00},
	{0x4, danica_1080p_video_on_cmd4, 0x00},
	{0x4, danica_1080p_video_on_cmd5, 0x00},
	{0x4, danica_1080p_video_on_cmd6, 0x00},
	{0x4, danica_1080p_video_on_cmd7, 0x00},
	{0x4, danica_1080p_video_on_cmd8, 0x00},
	{0x4, danica_1080p_video_on_cmd9, 0x00},
	{0x4, danica_1080p_video_on_cmd10, 0x00},
	{0x4, danica_1080p_video_on_cmd11, 0x00},
	{0x4, danica_1080p_video_on_cmd12, 0x00},
	{0x4, danica_1080p_video_on_cmd13, 0x00},
	{0x4, danica_1080p_video_on_cmd14, 0x00},
	{0x4, danica_1080p_video_on_cmd15, 0x00},
	{0x4, danica_1080p_video_on_cmd16, 0x00},
	{0x4, danica_1080p_video_on_cmd17, 0x00},
	{0x4, danica_1080p_video_on_cmd18, 0x00},
	{0x4, danica_1080p_video_on_cmd19, 0x00},
	{0x4, danica_1080p_video_on_cmd20, 0x00},
	{0x4, danica_1080p_video_on_cmd21, 0x00},
	{0x4, danica_1080p_video_on_cmd22, 0x00}
};

#define DANICA_1080P_VIDEO_ON_COMMAND 23


static char danica_1080p_videooff_cmd0[] = {
	0x28, 0x00, 0x05, 0x80
};

static char danica_1080p_videooff_cmd1[] = {
	0x53, 0x00, 0x15, 0x80
};

static char danica_1080p_videooff_cmd2[] = {
	0x10, 0x00, 0x05, 0x80
};

static char danica_1080p_videooff_cmd3[] = {
	0x78, 0xFF, 0xFF, 0x80
};

static struct mipi_dsi_cmd danica_1080p_video_off_command[] = {
	{0x4, danica_1080p_videooff_cmd0, 0x00},
	{0x4, danica_1080p_videooff_cmd1, 0x00},
	{0x4, danica_1080p_videooff_cmd2, 0x00},
	{0x4, danica_1080p_videooff_cmd3, 0x00}
};

#define DANICA_1080P_VIDEO_OFF_COMMAND 4


static struct command_state danica_1080p_video_state = {
	0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info danica_1080p_video_command_panel = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info danica_1080p_video_video_panel = {
	16, 0, 0, 0, 1, 1, 1, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration danica_1080p_video_lane_config = {
	4, 0, 1, 1, 1, 1
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t danica_1080p_video_timings[] = {
	0xD2, 0x30, 0x20, 0x00, 0x5E, 0x62, 0x26, 0x34, 0x26, 0x03, 0x04, 0x00
};

static struct panel_timing danica_1080p_video_timing_info = {
	0, 4, 0x7E, 0x0A
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence danica_1080p_video_reset_seq = {
	{1, 20, 20, }, {0, 0, 1, }, 20
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight danica_1080p_video_backlight = {
	1, 1, 255, 100, 1, "PMIC_8974"
};

#endif /*_PANEL_DANICA_1080P_VIDEO_H_*/
