/* Copyright (c) 2017, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_TDO_HD0466K40002_0810_H_
#define _PANEL_TDO_HD0466K40002_0810_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config tdo_hd0466k40002_0810_panel_data = {
	"qcom,mdss_dsi_tdo_hd0466k40002_0810", "dsi:0:", "qcom,mdss-dsi-panel",
	8, 0, "DISPLAY_1", 0, 0, 60, 1, 0, 0, 0, 0, 0, 0, 386100000, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution tdo_hd0466k40002_0810_panel_res = {
	720, 1280, 164, 140, 8, 0, 6, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info tdo_hd0466k40002_0810_color = {
	24, 2, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/
static char tdo_hd0466k40002_0810_on_cmd0[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd1[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd2[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd3[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd4[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd5[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd6[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd7[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd8[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd9[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd10[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd11[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd12[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd13[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd14[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd15[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd16[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd17[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd18[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd19[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd20[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd21[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd22[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd23[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd24[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd25[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd26[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd27[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd28[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd29[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd30[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd31[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd32[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd33[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd34[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd35[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd36[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd37[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd38[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd39[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd40[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd41[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd42[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd43[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd44[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd45[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd46[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd47[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd48[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd49[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd50[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd51[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd52[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd53[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd54[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd55[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd56[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd57[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd58[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd59[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd60[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd61[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd62[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd63[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd64[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd65[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd66[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd67[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd68[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd69[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd70[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd71[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd72[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd73[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd74[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd75[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd76[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd77[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd78[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd79[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd80[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd81[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd82[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd83[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd84[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd85[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd86[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd87[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd88[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd89[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd90[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd91[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd92[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd93[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd94[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd95[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd96[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd97[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd98[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd99[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd100[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd101[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd102[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd103[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd104[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd105[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd106[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd107[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd108[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd109[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd110[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd111[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd112[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd113[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd114[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd115[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd116[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd117[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd118[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd119[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd120[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd121[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd122[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd123[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd124[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd125[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd126[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd127[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd128[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd129[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd130[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd131[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd132[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd133[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd134[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd135[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd136[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd137[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd138[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd139[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd140[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd141[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd142[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd143[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd144[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd145[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd146[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd147[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd148[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd149[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd150[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd151[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd152[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd153[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd154[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd155[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd156[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd157[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd158[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd159[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd160[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd161[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd162[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd163[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd164[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd165[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd166[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd167[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd168[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd169[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd170[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd171[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd172[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd173[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd174[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd175[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd176[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd177[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd178[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd179[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd180[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd181[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd182[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd183[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd184[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd185[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd186[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd187[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd188[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd189[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd190[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd191[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd192[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd193[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd194[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd195[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd196[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd197[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd198[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd199[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd200[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd201[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd202[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd203[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd204[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd205[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd206[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd207[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd208[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd209[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd210[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd211[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd212[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd213[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd214[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd215[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd216[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd217[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd218[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd219[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd220[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd221[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd222[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd223[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd224[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd225[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd226[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd227[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd228[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd229[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd230[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd231[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd232[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd233[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd234[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd235[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd236[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd237[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd238[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd239[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd240[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd241[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd242[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd243[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd244[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd245[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd246[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd247[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd248[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd249[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd250[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd251[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd252[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd253[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd254[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd255[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd256[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd257[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd258[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd259[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd260[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd261[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd262[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd263[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd264[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd265[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd266[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd267[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd268[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd269[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd270[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd271[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd272[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd273[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd274[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd275[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd276[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd277[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd278[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd279[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd280[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd281[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd282[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd283[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd284[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd285[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd286[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd287[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd288[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd289[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd290[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd291[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd292[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd293[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd294[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd295[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd296[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd297[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd298[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd299[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd300[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd301[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd302[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd303[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd304[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd305[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd306[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd307[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd308[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd309[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd310[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd311[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd312[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd313[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd314[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd315[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd316[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd317[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd318[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd319[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd320[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd321[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd322[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd323[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd324[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd325[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd326[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd327[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd328[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd329[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd330[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd331[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd332[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd333[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd334[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd335[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd336[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd337[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd338[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd339[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd340[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd341[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd342[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd343[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd344[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd345[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd346[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd347[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd348[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd349[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd350[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd351[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd352[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd353[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd354[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd355[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd356[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd357[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd358[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd359[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd360[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd361[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd362[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd363[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd364[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd365[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd366[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd367[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd368[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd369[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd370[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd371[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd372[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd373[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd374[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd375[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd376[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd377[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd378[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd379[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd380[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd381[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd382[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd383[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd384[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd385[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd386[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd387[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd388[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd389[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd390[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd391[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd392[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd393[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd394[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd395[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd396[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd397[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd398[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd399[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd400[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd401[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd402[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd403[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd404[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd405[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd406[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd407[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd408[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd409[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd410[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd411[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd412[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd413[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd414[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd415[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd416[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd417[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd418[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd419[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd420[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd421[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd422[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd423[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd424[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd425[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd426[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd427[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd428[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd429[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd430[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd431[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd432[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd433[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd434[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd435[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd436[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd437[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd438[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd439[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd440[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd441[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd442[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd443[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd444[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd445[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd446[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd447[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd448[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd449[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd450[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd451[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd452[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd453[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd454[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd455[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd456[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd457[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd458[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd459[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd460[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd461[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd462[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd463[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd464[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd465[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd466[] = { };
	
static char tdo_hd0466k40002_0810_on_cmd467[] = { };
	
static struct mipi_dsi_cmd tdo_hd0466k40002_0810_on_command[] = {
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

};

#define TDO_HD0466K40002_0810_ON_COMMAND 0


static struct mipi_dsi_cmd tdo_hd0466k40002_0810_off_command[] = {

};

#define TDO_HD0466K40002_0810_OFF_COMMAND 0


static struct command_state tdo_hd0466k40002_0810_state = {
	0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info tdo_hd0466k40002_0810_command_panel = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info tdo_hd0466k40002_0810_video_panel = {
	8, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration tdo_hd0466k40002_0810_lane_config = {
	4, 0, 1, 1, 1, 1
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t tdo_hd0466k40002_0810_timings[] = {
	0x7B, 0x1E, 0x14, 0x0, 0x44, 0x4A, 0x18, 0x22, 0x19, 0x3, 0x4
};

static struct panel_timing tdo_hd0466k40002_0810_timing_info = {
	0, 4, 0xa4, 0x10
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence tdo_hd0466k40002_0810_reset_seq = {
	{1, 20, 20, }, {0, 0, 1, }, 20
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight tdo_hd0466k40002_0810_backlight = {
	1, 1, 255, 100, 2, "PMIC_8941"
};

#endif /*_PANEL_TDO_HD0466K40002_0810_H_*/
