/* Copyright (c) 2017, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_TEQUILA_720P_VIDEO_H_
#define _PANEL_TEQUILA_720P_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config tequila_720p_video_panel_data = {
	"qcom,mdss_dsi_tequila_720p_video", "dsi:0:", "qcom,mdss-dsi-panel",
	8, 0, "DISPLAY_1", 0, 0, 60, 1, 0, 0, 0, 0, 0, 0, 386100000, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution tequila_720p_video_panel_res = {
	720, 1280, 60, 40, 50, 0, 14, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info tequila_720p_video_color = {
	24, 2, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/
static char tequila_720p_video_on_cmd0[] = {
	0xFF, 0x0a, 0x00, 0x80
};

static char tequila_720p_video_on_cmd1[] = {
	0x11, 0x00, 0x05, 0x80
};

static char tequila_720p_video_on_cmd2[] = {
	0xFF, 0x78, 0x00, 0x80
};

static char tequila_720p_video_on_cmd3[] = {
	0x53, 0x28, 0x15, 0x80
};

static char tequila_720p_video_on_cmd4[] = {
	0x51, 0x80, 0x15, 0x80
};

static char tequila_720p_video_on_cmd5[] = {
	0xFF, 0x78, 0x00, 0x80
};

static char tequila_720p_video_on_cmd6[] = {
	0x29, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd tequila_720p_video_on_command[] = {
	{0x4, tequila_720p_video_on_cmd0, 0x00},
	{0x4, tequila_720p_video_on_cmd1, 0x00},
	{0x4, tequila_720p_video_on_cmd2, 0x00},
	{0x4, tequila_720p_video_on_cmd3, 0x00},
	{0x4, tequila_720p_video_on_cmd4, 0x00},
	{0x4, tequila_720p_video_on_cmd5, 0x00},
	{0x4, tequila_720p_video_on_cmd6, 0x00}
};

#define TEQUILA_720P_VIDEO_ON_COMMAND 7


static char tequila_720p_videooff_cmd0[] = {
	0x28, 0x00, 0x05, 0x80
};

static char tequila_720p_videooff_cmd1[] = {
	0x53, 0x00, 0x15, 0x80
};

static char tequila_720p_videooff_cmd2[] = {
	0x10, 0x00, 0x05, 0x80
};

static char tequila_720p_videooff_cmd3[] = {
	0xFF, 0x78, 0x00, 0x80
};

static struct mipi_dsi_cmd tequila_720p_video_off_command[] = {
	{0x4, tequila_720p_videooff_cmd0, 0x00},
	{0x4, tequila_720p_videooff_cmd1, 0x00},
	{0x4, tequila_720p_videooff_cmd2, 0x00},
	{0x4, tequila_720p_videooff_cmd3, 0x00}
};

#define TEQUILA_720P_VIDEO_OFF_COMMAND 4


static struct command_state tequila_720p_video_state = {
	0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info tequila_720p_video_command_panel = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info tequila_720p_video_video_panel = {
	4, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration tequila_720p_video_lane_config = {
	4, 0, 1, 1, 1, 1
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t tequila_720p_video_timings[] = {
	0x7B, 0x1A, 0x10, 0x00, 0x3C, 0x42, 0x14, 0x1C, 0x15, 0x03, 0x04, 0x00
};

static struct panel_timing tequila_720p_video_timing_info = {
	0, 4, 0x04, 0x1a
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence tequila_720p_video_reset_seq = {
	{1, 20, 20, }, {0, 0, 1, }, 20
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight tequila_720p_video_backlight = {
	1, 1, 255, 100, 2, "PMIC_8941"
};

#endif /*_PANEL_TEQUILA_720P_VIDEO_H_*/
